language: python
dist: xenial
python:
  - "3.6"
before_install:
  - sudo apt-get install -y libspatialindex-dev
install:
  - pip install -r requirements.txt
  - pip install mypy flake8
  - pip install -e .
script:
  - flake8 elbridge tests
  - pytest